version: '2.1'
services:
    postgresB:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflowB
            - POSTGRES_PASSWORD=airflowB
            - POSTGRES_DB=airflowB

    webserverB:
        image: puckel/docker-airflow:1.10.4
        restart: always
        depends_on:
            - postgresB
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - POSTGRES_USER=airflowB
            - POSTGRES_PASSWORD=airflowB
            - POSTGRES_DB=airflowB
            - POSTGRES_HOST=postgresB
            - AIRFLOW__WEBSERVER__DAG_DIR_LIST_INTERVAL=10
        volumes:
            - ./dags:/usr/local/airflow/dags
        ports:
            - "8081:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3